version: '3.8'
services:
  php:
    build: ./
    container_name: php
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./students.sql:/docker-entrypoint-initdb.d/students_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students_db
      MYSQL_USER: student_list_user
      MYSQL_PASSWORD: student_list_pass
    ports:
      - 3306:3306
    healthcheck:
        test: mysql -h mysql -P 3306 -uroot -proot
        interval: 5s
        retries: 60